### ISSUE TITLE
Should we cut on mask_frac?

### ISSUE THREAD

**Issue by esheldon** [esheldon/y1shearcat-bugs#4]
Figure from Daniel Gruen

![maskfrac](https://cloud.githubusercontent.com/assets/621661/23569449/598eb2d6-002d-11e7-80fa-523e6d158724.png)

**Comment by esheldon** [comment]
Example such object:

![des0510-4123-r-3049195008-0 990](https://cloud.githubusercontent.com/assets/621661/23570158/06227890-0031-11e7-838a-7cde79704bd0.png)

**Comment by esheldon** [comment]
@danielgruen I posted some pictures to you.  Are we happy not cutting on these?

**Comment by danielgruen** [comment]
Had a look at the sample -- these seem to consist of objects with near-blends or somewhat more distant but bright neighbors. My feeling is that the uncertainty in including these is in the neighbor budget, and the latter might get smaller if we make a cut in mask_fract. The level to cut at seems kind of arbitrary though. Will run a few tests of the MOF vs. non-MOF tangential shear with cuts at different mask_frac.

**Comment by esheldon** [comment]
We decided not to put this into the `flags_select`
