### ISSUE TITLE
objects with negative fluxes should be flagged

### ISSUE THREAD

**Issue by danielgruen** [esheldon/y1shearcat-bugs#5]
The way flags_select is defined now, objects that have negative flux measurements (in MOF or metacal) can still have zero flags. It's very few of them, but they do exist.

Negative flux measurement is not handled properly by BPZ somewhere along the way. In fact, I think the photo-z people like to make a 'crazy color' cut, that removes even a near-dropout.

The minimum we must do (if we can't change photo-z) is to flag objects with MOF or metacal (sheared) flux in any of griz <= 0 with a new bit in flags_select. This applies to a <per-mille fraction of galaxies in metacal and im3shape. 

Another option is to apply the photo-z crazy color cut. Querying Ben and Will about that.

**Comment by esheldon** [comment]
Any progress querying Ben and Will?

**Comment by esheldon** [comment]
Here is the breakdown with the flux cut
```
         96561/1000000 with mof_flags 
        106531/1000000 with low mof_flux_g < 1e-06
         78059/1000000 with low mof_flux_r < 1e-06
         76075/1000000 with low mof_flux_i < 1e-06
         76245/1000000 with low mof_flux_z < 1e-06
        192568/1000000 with badregion set
        112260/1000000 with gold flags set
         68311/1000000 with flags set
        568340/1000000 with flags==0 and low Tratio noshear
        279936/1000000 with flags==0 and low snr noshear
          6387/1000000 with low flux_r < 1e-06
          2659/1000000 with low flux_i < 1e-06
          4737/1000000 with low flux_z < 1e-06
        568338/1000000 with flags==0 and low Tratio 1p
        279902/1000000 with flags==0 and low snr 1p
          6408/1000000 with low flux_r_1p < 1e-06
          2631/1000000 with low flux_i_1p < 1e-06
          4772/1000000 with low flux_z_1p < 1e-06
        568213/1000000 with flags==0 and low Tratio 1m
        279939/1000000 with flags==0 and low snr 1m
          6410/1000000 with low flux_r_1m < 1e-06
          2658/1000000 with low flux_i_1m < 1e-06
          4762/1000000 with low flux_z_1m < 1e-06
        568319/1000000 with flags==0 and low Tratio 2p
        279873/1000000 with flags==0 and low snr 2p
          6394/1000000 with low flux_r_2p < 1e-06
          2632/1000000 with low flux_i_2p < 1e-06
          4766/1000000 with low flux_z_2p < 1e-06
        568350/1000000 with flags==0 and low Tratio 2m
        279918/1000000 with flags==0 and low snr 2m
          6388/1000000 with low flux_r_2m < 1e-06
          2656/1000000 with low flux_i_2m < 1e-06
          4746/1000000 with low flux_z_2m < 1e-06

```

**Comment by esheldon** [comment]
I saw eli has said "If you cut all flags_gold == 0 then you impose the 'Crazy color' cut." But those are not on MOF fluxes.

**Comment by danielgruen** [comment]
Will does not explicitly complain, Ben hasn't replied yet

**Comment by esheldon** [comment]
I've created the catalogs, need people to let me know if it all is making sense.

**Comment by hoyleb** [comment]
FYi the photo-z don't impose the crazy color cuts [we don't care], that comes from higher up the food chain.

Ben
